name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on:
      - self-hosted
      - linux
    container:
      image: zlondrej/playground:volumetric-clouds-build
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: show workdir
      run: pwd
    - name: show home
      run: echo $HOME
    - name: show mess
      run: ls -al
    - name: make mess
      run: touch trash
